<?php
$order = $block->getOrder();
$helper = $this->getHelper();
$viewType = $helper->getGeneralConfig('view_type');
?>
<div class="checkout-success">
    <?php if($order->getIncrementId()):?>
        <?php if ($block->getCustomerId()) :?>
            <p><?php echo __("Your order number is: $order->getIncrementId()");?>
            </p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.',$order->getIncrementId()) ?></p>
        <?php endif;?>
        <p><?php echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>
</div>
<?php
    if( !empty( $helper->getGeneralConfig('view_type') ) && $helper->getGeneralConfig('view_type') != "no" ):
        if( $helper->getGeneralConfig('view_type') == 'popup' ):?>
          <script>alert("Popup Selected.");</script>
  <?php else: ?>
            <div>
                <div class="message-show-page" style="display: none;color:red"> </div>
                <br/>
                <input type="checkbox" value="true" name="wants_subscribe-page" id="wants_subscribe-page" />
                <input type="hidden" value="<?php echo $order->getCustomerEmail(); ?>" id="email-address" name="email-address" />
                <input type="button" name="ajax-call" id="ajax-subscriber" value="Subscribe">
            </div>
        <?php endif;
    endif;
?>

<script type="text/javascript">
    require(['jquery'], function(){
        jQuery('#ajax-subscriber').on('click', function(event){
            if( jQuery("#wants_subscribe-page").prop("checked") == true ){
                var email = jQuery("#email-address").val();
                jQuery.ajax({
                    url: '<?php echo $block->getAjaxUrl(); ?>',
                    type: "POST",
                    dataType: 'json',
                    context: this,
                    data: {
                        email: email
                    },
                    success: function (response) {
                        console.log( response );
                        if( response.status == true ){
                            jQuery('.message-show-page').html(response.msg);
                            jQuery('.message-show-page').show();
                        }
                    }
                });
            }else{
                alert("Please click checkbox first.");
            }
        });
    });
</script>